// import { Inter } from "next/font/google";
// import styles from './styles/Login.module.css';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
        
//       <body className={inter.className}>
//         <header style={{backgroundColor:"lightblue", padding: "1rem",}}>
//             this is header
//         </header>
//         {children}
//         </body>
     
//     </html>
//   );
// }
import React from 'react'

function layout({children}) {
  return (
    <div>
      <h1>This is layout page
      </h1>
      {children}
    </div>
  )
}

export default layout
export function generateMetadata(){
  return{
    title:"welcome custome meta data",
    description:"this is custome metadata"
  }
}